Dev 0.1
kubesphere/monitoring-dashboard pull request #9
Opened 2021-02-09 09:18 UTC by zhu733756

add a converter tool

2021-02-20 05:25 UTC, benjaminhuo requested changes

2021-02-20 05:25 UTC, benjaminhuo commented on api/v1alpha1/panels/dashboard_penels_types.go
> +// +kubebuilder:object:generate=true
dashboard_penels_types.go  should be dashboard_panels_types.go  ?

2021-02-20 05:25 UTC, benjaminhuo commented on api/v1alpha1/panels/bargauge_types.go
> +	Options BarGaugeOptions `json:"options,omitempty,omitempty" yaml:"options,omitempty,omitempty"`
if the member of a struct is of type struct, then this member should be a pointer to a struct type.
pls check all relevant code

2021-02-20 05:25 UTC, benjaminhuo commented on config/prometheus/es-daemonset.yaml
> +kind: DaemonSet
These files are not necessary:

config/prometheus/grafana-svc.yaml
config/prometheus/grafana-deploy.yaml
config/prometheus/es_servicemonitor.yaml
config/prometheus/es-daemonset.yaml

2021-02-20 05:25 UTC, benjaminhuo commented on tools/converter/json.go
> +		Metadata:   map[string]string{"name": name, "namespace": ns},
ClusterDashboard shouldn't have a namespace

2021-06-23 03:00 UTC, junotx requested changes

2021-06-23 03:00 UTC, junotx commented on README.md
> +
Only three of the four supported panel types are listed

2021-06-23 03:00 UTC, junotx commented on Makefile
> +	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.5 ;\
This version of the controller-gen generated CRD version for `apiextensions.k8s.io/v1beta1`, but the latest code has upgraded it to v0.4.1 which generates CRDs for the `apiextensions.k8s.io/v1` version required by KubeSphere3.1+

2021-06-23 03:00 UTC, junotx commented on api/v1alpha1/panels/dashboard_penels_types.go
> +type Panel struct {
It looks like `Panel` already supports configuring multiple types of panels, but why are there still other definitions like `Graph`, `Table`, `Text` and so on.

2021-06-23 03:32 UTC, junotx commented
The conflicts can also be resolved, and compatibility with previous original configuration is recommended, which can be verified by unit testing @zhu733756

2021-06-24 01:39 UTC, zhu733756 commented on api/v1alpha1/panels/dashboard_penels_types.go
> +type Panel struct {
Have got two question as followings:
- Currently，we only support panel types like 'graph/row/singlestat',  the other types do not need to support?
- The detailed definition of the panel types no need to convert to the dashboard? The style of the console was a  fixed struct?

2021-06-24 01:40 UTC, zhu733756 commented on Makefile
> +	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.5 ;\
Will be fixed

2021-06-24 01:42 UTC, zhu733756 commented
> The conflicts can also be resolved, and compatibility with previous original configuration is recommended, which can be verified by unit testing @zhu733756

Would be fixed. Pls answer my two questions above and  I would readjust it according to your suggestion.

2021-06-28 06:12 UTC, junotx commented on api/v1alpha1/panels/dashboard_penels_types.go
> +type Panel struct {
For the first, other types of support can be added. And the second, i don't quite understand what you mean

2021-07-02 03:02 UTC, junotx requested changes

2021-07-02 03:02 UTC, junotx commented on api/v1alpha1/dashboard_types.go
> +// }
These can be deleted directly instead of comments

2021-07-02 03:02 UTC, junotx commented on api/v1alpha2/dashboard_conversion.go
> +
Why is the `request` attribute used, and i counld not find it in the grafana template struct

2021-07-02 03:02 UTC, junotx commented on api/v1alpha2/panels/dashboard_penels_types.go
> +		}
`MarshalJSON` has handling for `row` case, but not here

2021-07-02 03:28 UTC, zhu733756 commented on api/v1alpha1/dashboard_types.go
> +// }
would be fixed

2021-07-02 03:29 UTC, zhu733756 commented on api/v1alpha2/panels/dashboard_penels_types.go
> +		}
Row struct is empty, these comments would be used for feature if we want to add some fields.

2021-07-02 03:37 UTC, zhu733756 commented on api/v1alpha2/dashboard_conversion.go
> +
it refers to [the dark definition]( https://pkg.go.dev/github.com/K-Phoen/grabana/decoder#DashboardVariable),  would be fixed.

2021-07-02 08:01 UTC, junotx approved these changes
/lgtm

2021-07-02 08:02 UTC, merged